///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuizModel {
/*
{
  "name": "unit 2",
  "desc": "math test with mr ahmed",
  "material": "Math",
  "date": "25 / 6 /2023"
}
*/

  String? name;
  String? desc;
  String? material;
  String? date;

  QuizModel({
    this.name,
    this.desc,
    this.material,
    this.date,
  });
  QuizModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    desc = json['desc']?.toString();
    material = json['material']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['desc'] = desc;
    data['material'] = material;
    data['date'] = date;
    return data;
  }
}
